# Markdown renderer configuration
[goldmark.renderer]
unsafe = true

[tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
tabWidth = 4
style = "doom-one"
